export const stopskey = {
    "Hong Kong": "HOK",
    "Kowloon": "KOW",
    "Olympic": "OLY",
    "Nam Cheong": "NAC",
    "Lai King": "LAK",
    "Tsing Yi": "TSY",
    "Sunny Bay": "SUN",
    "Tung Chung": "TUC",
    "Wu Kai Sha": "WKS",
    "Ma On Shan": "MOS",
    "Heng On": "HEO",
    "Tai Shui Hang": "TSH",
    "Shek Mun": "SHM",
    "City One": "CIO",
    "Sha Tin Wai": "STW",
    "Che Kung Temple": "CKT",
    "Tai Wai": "TAW",
    "Hin Keng": "HIK",
    "Diamond Hill": "DIH",
    "Kai Tak": "KAT",
    "Sung Wong Toi": "SUW",
    "To Kwa Wan": "TKW",
    "Ho Man Tin": "HOM",
    "Hung Hom": "HUH",
    "East Tsim Sha Tsui": "ETS",
    "Austin": "AUS",
    "Mei Foo": "MEF",
    "Tsuen Wan West": "TWW",
    "Kam Sheung Road": "KSR",
    "Yuen Long": "YUL",
    "Long Ping": "LOP",
    "Tin Shui Wai": "TIS",
    "Siu Hong": "SIH",
    "Tuen Mun": "TUM",
    "North Point": "NOP",
    "Quarry Bay": "QUB",
    "Yau Tong": "YAT",
    "Tiu Keng Leng": "TIK",
    "Tseung Kwan O": "TKO",
    "LOHAS Park": "LHP",
    "Hang Hau": "HAH",
    "Po Lam": "POA",
    "Admiralty": "ADM",
    "Exhibition Centre": "EXC",
    "Mong Kok East": "MKK",
    "Kowloon Tong": "KOT",
    "Sha Tin": "SHT",
    "Fo Tan": "FOT",
    "Racecourse": "RAC",
    "University": "UNI",
    "Tai Po Market": "TAP",
    "Tai Wo": "TWO",
    "Fanling": "FAN",
    "Sheung Shui": "SHS",
    "Lo Wu": "LOW",
    "Lok Ma Chau": "LMC",
    "Ocean Park": "OCP",
    "Wong Chuk Hang": "WCH",
    "Lei Tung": "LET",
    "South Horizons": "SOH",
    "Central": "CEN",
    "Tsim Sha Tsui": "TST",
    "Jordan": "JOR",
    "Yau Ma Tei": "YMT",
    "Mong Kok": "MOK",
    "Prince Edward": "PRE",
    "Sham Shui Po": "SSP",
    "Cheung Sha Wan": "CSW",
    "Lai Chi Kok": "LCK",
    "Kwai Fong": "KWF",
    "Kwai Hing": "KWH",
    "Tai Wo Hau": "TWH",
    "Tsuen Wan": "TSW",
    "Kennedy Town": "KET",
    "HKU": "HKU",
    "Sai Ying Pun": "SYP",
    "Sheung Wan": "SHW",
    "Wan Chai": "WAC",
    "Causeway Bay": "CAB",
    "Tin Hau": "TIH",
    "Fortress Hill": "FOH",
    "North Point": "NOP",
    "Quarry Bay": "QUB",
    "Tai Koo": "TAK",
    "Sai Wan Ho": "SWH",
    "Shau Kei Wan": "SKW",
    "Heng Fa Chuen": "HFC",
    "Chai Wan": "CHW",
    "Whampoa": "WHA",
    "Ho Man Tin": "HOM",
    "Yau Ma Tei": "YMT",
    "Mong Kok": "MOK",
    "Prince Edward": "PRE",
    "Shek Kip Mei": "SKM",
    "Kowloon Tong": "KOT",
    "Lok Fu": "LOF",
    "Wong Tai Sin": "WTS",
    "Diamond Hill": "DIH",
    "Choi Hung": "CHH",
    "Kowloon Bay": "KOB",
    "Ngau Tau Kok": "NTK",
    "Kwun Tong": "KWT",
    "Lam Tin": "LAT",
    "Yau Tong": "YAT",
    "Tiu Keng Leng": "TIK",
    "Hong Kong": "HOK",
    "Kowloon": "KOW",
    "Tsing Yi": "TSY",
    "Airport": "AIR",
    "AsiaWorld Expo": "AWE"
  }